### ISSUE TITLE
How to open browser frame directly 

### ISSUE THREAD

**Issue by joukhar** [MakeOpinionGmbH/cpx-research-SDK-Flutter#3]
How to open browser frame directly without and widgets with app id and user id
i tried `showBrowser` method but i can't pass any params

**Comment by crab-by** [comment]
Hi @joukhar, we added a simple function which adds exactly what you were looking for. No need for any widgets, just a simple function call with the config as parameter, find more details in our [ReadMe - Getting Started](https://github.com/MakeOpinionGmbH/cpx-research-SDK-Flutter?tab=readme-ov-file#getting-started-easiest) section.

**Comment by joukhar** [comment]
fantastic :heart:
